# Generated by Django 3.0.4 on 2020-03-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='shortDesc',
            field=models.CharField(default='Default value short desc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='thumb',
            field=models.FileField(default='img/default', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='img/'),
        ),
    ]
