# Generated by Django 3.0.4 on 2020-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200315_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumb',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
