# Generated by Django 3.0.4 on 2020-03-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('desc', models.TextField(max_length=512)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='uploads/')),
                ('active', models.BooleanField(default=True)),
                ('link', models.URLField(max_length=255)),
            ],
        ),
    ]
