# Generated by Django 3.0.4 on 2020-03-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_slider',
            name='image',
            field=models.FileField(upload_to='img/'),
        ),
    ]
