# Generated by Django 3.0.4 on 2020-03-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200314_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_slider',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
