# Generated by Django 3.0.4 on 2020-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200315_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_slider',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
